[package]
name = "load_sql2es"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
elasticsearch = "9.0.0-alpha.1"
serde = "~1"
serde_json = "~1"
tokio = { version = "1", features = ["full"] }
url = { version = "2", features = ["serde"] }

